version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.yourdomain.com/api
      - NEXT_PUBLIC_APP_ENV=production
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./backend/logs:/app/logs
      - uploads:/app/uploads
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=timelapse_journal_prod
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_prod_data:
  uploads:

networks:
  app-network:
    driver: bridge