version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - DB_PATH=/app/data/database.sqlite
      - JWT_ACCESS_SECRET=your_super_secret_jwt_access_key_change_this_in_production
      - JWT_REFRESH_SECRET=your_super_secret_jwt_refresh_key_change_this_in_production
      - JWT_ACCESS_EXPIRY=15m
      - JWT_REFRESH_EXPIRY=7d
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
      - ./backend/package.json:/app/package.json
    command: npm run dev